const swaggerJSDoc = require('swagger-jsdoc');
const swaggerUi = require('swagger-ui-express');
const birds = require('./routes/test-routes')
const express = require('express');
const app = express();

const options = {
    swaggerDefinition: {
        // Like the one described here: https://swagger.io/specification/#infoObject
        info: {
            title: 'Test API',
            version: '1.0.0',
            description: 'Test Express API with autogenerated swagger doc',
        },
    },
    // List of files to be processes. You can also set globs './routes/*.js'
    apis: ['./routes/test-routes.js', './*.js', './routes/*.js'],
}

const specs = swaggerJSDoc(options);

console.log(specs);

app.use('/birds', birds)
app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(specs));

app.get('/', function (req, res) {
    res.send("Hello world!");
});

app.listen(3000);